// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL7vIFY0qYWpP8v8ugoJdNMKdgkTvYtMU',
    appId: '1:1091481839862:web:400db599da6174833924d7',
    messagingSenderId: '1091481839862',
    projectId: 'wallyapp-34964',
    authDomain: 'wallyapp-34964.firebaseapp.com',
    databaseURL: 'https://wallyapp-34964-default-rtdb.firebaseio.com',
    storageBucket: 'wallyapp-34964.appspot.com',
    measurementId: 'G-N3B0EBGLW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO99h3HK1geDxCSs_a_piOdp4nEtRs6Ug',
    appId: '1:1091481839862:android:07dd228f9def4efe3924d7',
    messagingSenderId: '1091481839862',
    projectId: 'wallyapp-34964',
    databaseURL: 'https://wallyapp-34964-default-rtdb.firebaseio.com',
    storageBucket: 'wallyapp-34964.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_YvsudHSEeAAsGZleeHQ62ezEkGFIfCc',
    appId: '1:1091481839862:ios:7971bfe7c026a70c3924d7',
    messagingSenderId: '1091481839862',
    projectId: 'wallyapp-34964',
    databaseURL: 'https://wallyapp-34964-default-rtdb.firebaseio.com',
    storageBucket: 'wallyapp-34964.appspot.com',
    androidClientId: '1091481839862-cgmoqjeu0deeetc1cb2o806kfgl53kio.apps.googleusercontent.com',
    iosClientId: '1091481839862-87ps8qlros6ikolm0auo869gc4uo6fqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallyapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_YvsudHSEeAAsGZleeHQ62ezEkGFIfCc',
    appId: '1:1091481839862:ios:7971bfe7c026a70c3924d7',
    messagingSenderId: '1091481839862',
    projectId: 'wallyapp-34964',
    databaseURL: 'https://wallyapp-34964-default-rtdb.firebaseio.com',
    storageBucket: 'wallyapp-34964.appspot.com',
    androidClientId: '1091481839862-cgmoqjeu0deeetc1cb2o806kfgl53kio.apps.googleusercontent.com',
    iosClientId: '1091481839862-87ps8qlros6ikolm0auo869gc4uo6fqj.apps.googleusercontent.com',
    iosBundleId: 'com.example.wallyapp',
  );
}
